apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-web
  template:
    metadata: 
      labels:
        app: java-web
    spec:
      containers:
      - name: front
        image: alesblaze/bookstore:latest
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-front-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 31201
  selector:
    app: java-web
