apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata: 
      labels:
        app: db
    spec:
      containers:
      - name: front
        image: alesblaze/bookstore:latest
        ports: 
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: service-db
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: db
