apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-aws
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  awsElasticBlockStore:
     volumeID: vol-0b05bbfc65f19da07
     fsType: ext4
