apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-disk-claim
  labels:
    - name: dstorage
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  # storageClassName: slow
